version: '3'

services:

  web:
    build: .
    volumes:
      - .:/code
    command: bash bin/docker-command.bash
    ports:
      - "8000:8000"   # application server
      - "35729:35729" # django live reload server
